const fs = require('fs');

const generateHistory = (initialVol, currentVol, hours) => {
  const history = [];
  const now = Date.now();
  const step = (initialVol - currentVol) / hours;
  for (let i = hours; i >= 0; i--) {
    history.push({
      timestamp: now - i * 3600000,
      volume: Math.round(initialVol - step * (hours - i))
    });
  }
  return history;
};

const devices = {
  "IV-DEVICE-001": {
    "id": "IV-DEVICE-001",
    "patientName": "Jane Doe",
    "patientAge": 45,
    "patientGender": "Female",
    "room": "301",
    "bed": "A",
    "medicineName": "Saline 0.9%",
    "ivFluidType": "Crystalloid",
    "battery": 85,
    "status": "normal",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 4,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "Post-op recovery",
    "totalVolume": 1000,
    "infusedVolume": 450,
    "flowRate": 125, // mL/hr
    "history": generateHistory(1000, 550, 4) // 1000 to 550 over 4 hours
  },
  "IV-DEVICE-002": {
    "id": "IV-DEVICE-002",
    "patientName": "John Smith",
    "patientAge": 62,
    "patientGender": "Male",
    "room": "302",
    "bed": "B",
    "medicineName": "Dextrose 5%",
    "ivFluidType": "Dextrose",
    "battery": 72,
    "status": "normal",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 3,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "",
    "totalVolume": 500,
    "infusedVolume": 100,
    "flowRate": 50,
    "history": generateHistory(500, 400, 2)
  },
  "IV-DEVICE-003": {
    "id": "IV-DEVICE-003",
    "patientName": "Mary Johnson",
    "patientAge": 38,
    "patientGender": "Female",
    "room": "303",
    "bed": "A",
    "medicineName": "Ringer's Lactate",
    "ivFluidType": "Ringer's Lactate",
    "battery": 23,
    "status": "low",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 2,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "Monitor closely",
    "totalVolume": 1000,
    "infusedVolume": 850,
    "flowRate": 150,
    "history": generateHistory(1000, 150, 6)
  },
  "IV-DEVICE-004": {
    "id": "IV-DEVICE-004",
    "patientName": "Robert Brown",
    "patientAge": 71,
    "patientGender": "Male",
    "room": "304",
    "bed": "C",
    "medicineName": "Saline 0.9%",
    "ivFluidType": "Crystalloid",
    "battery": 15,
    "status": "empty",
    "flowStatus": "clamped",
    "fluidPresent": false,
    "wifiSignal": 4,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "IV EMPTY — REPLACE NOW",
    "totalVolume": 500,
    "infusedVolume": 500,
    "flowRate": 0,
    "history": generateHistory(500, 0, 5)
  },
  "IV-DEVICE-005": {
    "id": "IV-DEVICE-005",
    "patientName": "Emily Davis",
    "patientAge": 29,
    "patientGender": "Female",
    "room": "305",
    "bed": "A",
    "medicineName": "Antibiotics",
    "ivFluidType": "Colloid",
    "battery": 91,
    "status": "normal",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 4,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "",
    "totalVolume": 250,
    "infusedVolume": 50,
    "flowRate": 100,
    "history": generateHistory(250, 200, 1)
  },
  "IV-DEVICE-006": {
    "id": "IV-DEVICE-006",
    "patientName": "",
    "patientAge": 0,
    "patientGender": "",
    "room": "306",
    "bed": "B",
    "medicineName": "",
    "ivFluidType": "Saline",
    "battery": 60,
    "status": "offline",
    "flowStatus": "clamped",
    "fluidPresent": false,
    "wifiSignal": 0,
    "sensorStatus": "inactive",
    "lastSeen": Date.now() - 3600000,
    "notes": "Device offline",
    "totalVolume": 1000,
    "infusedVolume": 0,
    "flowRate": 0,
    "history": []
  },
  "IV-DEVICE-007": {
    "id": "IV-DEVICE-007",
    "patientName": "Michael Scott",
    "patientAge": 50,
    "patientGender": "Male",
    "room": "307",
    "bed": "A",
    "medicineName": "Plasma",
    "ivFluidType": "Colloid",
    "battery": 45,
    "status": "normal",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 3,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "Stable condition",
    "totalVolume": 1000,
    "infusedVolume": 300,
    "flowRate": 75,
    "history": generateHistory(1000, 700, 4)
  },
  "IV-DEVICE-008": {
    "id": "IV-DEVICE-008",
    "patientName": "Sarah Connor",
    "patientAge": 33,
    "patientGender": "Female",
    "room": "308",
    "bed": "C",
    "medicineName": "Morphine",
    "ivFluidType": "Painkiller",
    "battery": 12,
    "status": "low",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 2,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "Battery critically low",
    "totalVolume": 100,
    "infusedVolume": 90,
    "flowRate": 10,
    "history": generateHistory(100, 10, 9)
  },
  "IV-DEVICE-009": {
    "id": "IV-DEVICE-009",
    "patientName": "James Bond",
    "patientAge": 48,
    "patientGender": "Male",
    "room": "309",
    "bed": "B",
    "medicineName": "Adrenaline",
    "ivFluidType": "Stimulant",
    "battery": 98,
    "status": "normal",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 4,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "",
    "totalVolume": 50,
    "infusedVolume": 25,
    "flowRate": 5,
    "history": generateHistory(50, 25, 5)
  },
  "IV-DEVICE-010": {
    "id": "IV-DEVICE-010",
    "patientName": "Tony Stark",
    "patientAge": 45,
    "patientGender": "Male",
    "room": "310",
    "bed": "A",
    "medicineName": "Palladium",
    "ivFluidType": "Experimental",
    "battery": 100,
    "status": "normal",
    "flowStatus": "open",
    "fluidPresent": true,
    "wifiSignal": 4,
    "sensorStatus": "active",
    "lastSeen": Date.now(),
    "notes": "",
    "totalVolume": 500,
    "infusedVolume": 200,
    "flowRate": 200,
    "history": generateHistory(500, 300, 1)
  }
};

fs.writeFileSync('devices.json', JSON.stringify(devices, null, 2));
console.log('Generated devices.json with flow rates and history.');
